tap "withgraphite/tap"

brew "chezmoi"
brew "fzf"
brew "starship"
# brew "httpie"
brew "curl"
brew "wget"
brew "git"
brew "htop"
brew "jq"
brew "ripgrep"
brew "vim"
brew "withgraphite/tap/graphite"

# not working right now
#vscode "ms-python.python"
#vscode "github.copilot"
#vscode "charliermarsh.ruff"
#vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
#vscode "hashicorp.terraform"
